### ISSUE TITLE
Certification error from XamlMetaDataProvider

### ISSUE THREAD

**Issue by jevansAN** [microsoft/xlang#481]
I am getting a certification error for a cppwinrt UWP app. I'll sub "AppName" for the actual name in the report: 
"XamlMetaDataProvider: Error Found: The general metadata correctness test detected the following errors:
The overloaded methods GetXamlType of type AppName.XamlMetaDataProvider in file AppName.winmd have the same number of in parameters without one that has DefaultOverloadAttribute. Exactly one method overload must have DefaultOverloadAttribute.
Impact if not fixed: Microsoft store doesn’t allow apps that don’t pass Windows Runtime Metadata Validation.
How to fix: Please ensure that the compiler you are using to generate your Windows Runtime types is up to date with with the Windows Runtime specifications."
I'm running VS 16.1.3 with cppwinrt 2.0.190605.7. I found a Nov. 2018 post at Windows Developer Feedback in which someone else reported the same thing for his cppwinrt app and was told this was a known bug in the VSIX and shortly to be fixed, but perhaps the fix was not completed - (?).

**Comment by kennykerr** [comment]
Sorry for the delay. This mildrt bug has been fixed as of build 18310 of the Windows SDK.

**Comment by jevansAN** [comment]
Thanks, Kenny. I know you've closed this, but I want to ask: I installed SDK 18362.0 not long ago and I am still getting a Midl error when creating the package for WinStore. The error is a little different now, however, and I'm not sure where to go with it.  
Error | MIDL2011 | [msg]unresolved type declaration [context]: Windows.UI.Xaml.Markup.IXamlMetadataProvider [ RuntimeClass 'Practica_Musica.XamlMetaDataProvider'  ] | Practica Musica | C:\Users\jeffevans\Practica Musica\Practica Musica\x64\Release\XamlMetaDataProvider.idl | 5 |

**Comment by kennykerr** [comment]
Not sure about that one. It sounds like MIDLRT is saying that you're missing the definition of IXamlMetadataProvider. Perhaps you can resolve this with a import/include in your IDL?

**Comment by jevansAN** [comment]
Hm. The error is in a generated file. I don't think #include can be used in an .idl file but maybe I'm not understanding what you mean by my IDL. This (pretty large) project was built on last year's Blank App for cppwinrt (which I love) and I wonder if there is something about the project that needs modifying. Other than building for release and certification it works great.

**Comment by jevansAN** [comment]
I should add this only happens when building the package. Compiles fine for debug and for release.

**Comment by jevansAN** [comment]
It might help this discussion if I created a cppwinrt blank app and tried packaging that to see if it does the same thing, but in the last VS 2019, 16.1.3 (I recently switched to community) I cannot find a way to create a blank cppwinrt UWP project. C++/CX, yes. C++/winrt, no. That would be a really useful feature for encouraging use of cppwinrt.

**Comment by kennykerr** [comment]
A simple repro would be great. You will need to install the VS extension. We're hoping to have the project templates integrated in a future update. https://aka.ms/cppwinrt/vsix

**Comment by jevansAN** [comment]
Ah - I had assumed all of cppwinrt came along with the Nuget Package! I can now create a blank app but this is going to take some study; I can build the release and deploy it but the blank app at the outset does not have a Store menu item for building a package as does my main project; probably depends on doing more research into configuring it. If I puzzle that out I'll see what I can come up with for a repro.

**Comment by jevansAN** [comment]
I think I'll have to give up on a repro for now - having built the template app Release and Deploy I cannot find a way to make the Store menu item appear in the project menu as it does in my own app. The Deploy command is also missing. Without those commands I can't build a package, and that is where the problem lies. If you know why the Store menu would fail to appear please let me know! I found one dev with a similar problem a few years ago, but nothing current.

**Comment by kennykerr** [comment]
Thanks for trying. You may be missing a Visual Studio installer option (although I'm not sure which one). I just created a project using the C++/WinRT Blank App template and then selected "Project > Store > Create App Packages" and it successfully built everything.

**Comment by jevansAN** [comment]
Kenny, I see you closed it but I might as well offer the rest of the info: turns out that the missing install component was "Desktop Development with C++." I had chosen only "Universal Windows Platform Development" because I'm creating a Universal Windows App. With the desktop tools installed, VS did offer the Store menu item and the template app did package and certify (except for images), without the Midl error. So the question now will be to find out why the Midl error in my main project. Might have to try recreating the whole thing from a blank template, something I don't like to contemplate but will undertake if  needed.

**Comment by BrentRe** [comment]
@jevansAN When you installed the UWP Development workload, did you select either one of the optional C++ UWP tool options? They certainly don't jump right out and advertise that you need to do this...

![image](https://user-images.githubusercontent.com/22179709/59793133-aac9ba00-928a-11e9-867e-17c7647c4113.png)

**Comment by jevansAN** [comment]
Thanks, Brent. Yes, I did checkmark C++(v142). But it seems one doesn't get the Store menu without also choosing Desktop Development with C++. I'm glad you stepped in here because you're the guy who knew about a midl issue last November that may relate to the one I report above. I originally had exactly the same error you commented on in Nov. 2018, for which you offered an update to the VSIX. Now I have just the MIDL2011 unresolved type declaration mentioned above and still can't find a way to make that go away.

**Comment by BrentRe** [comment]
The error on unknown Windows.UI.Xaml.Markup.IXamlMetadataProvider suggests either a) you are missing a reference to the .winmd file containing the definition of the type, or b) you are missing an 'import' in the IDL file to the IDL file containing the definition of the type.

In the first case, you likely missing a reference to the Windows.Foundation.UniversalApiContract.winmd file.

In the second case, you'd need an import of the appropriate XAML IDL file that defines the type. Not sure what that IDL file name is without access to a system.

Regardless, a default C++/WinRT project setup by the VSIX, by default, supports the approach (1) above. I suggest the 'easiest' path forward is to migrate your current source to the newly created project.

**Comment by jevansAN** [comment]
True that this was built on one of the early BlankApps offered for cppwinrt. Maybe something is missing. There are hundreds of source files and even more assets, so I've been avoiding the migration option. Yet I doubt I will be able to figure out what system file(s) are missing in the setup, so that could be the only way out. (BTW, when you refer to "the IDL file," do you mean App.idl? Both in this project and in the working template app that contains nothing but an empty namespace for the project name.

**Comment by BrentRe** [comment]
Current C++/WinRT based apps using MIDL 3 syntax and, typically, never contain an 'import' statement for system IDL files. The type definitions come of .winmd references passed to the MIDL compiler. You'd only typically 'import' another IDL file within the same project.

If all your project IDL files are empty, I've no idea why MIDL is looking for a definition of IXamlMetadataProvider. Maybe turn on Diagnostic MSBuild logging and see exactly what are the MIDL invocations and what source files the build is passing to MIDL.

**Comment by jevansAN** [comment]
Good inside info; I'll let you know if I find a solution other than migration.

**Comment by jevansAN** [comment]
Brent, I have rebuilt the whole thing - did give me a chance to better organize -there are three projects now sharing most of their code in a single solution. Each project was created using the C++/winrt template for a UWP app, and at least until I brought in all the source files from the previous app the three projects built and packaged correctly. But the trouble is that App.xaml and MainPage.xaml are not being generated. Does the template for C++/winrt require adjustment for this to happen? The project settings seem correct.

**Comment by jevansAN** [comment]
OK, cancel my comment above; the project has now compiled and packaged. There were some odd error messages, but they seem to have been spurious - VS apparently was confused by some path issues in the rebuilt project.

**Comment by jevansAN** [comment]
In case anyone sees this, it looks like the xaml problems were probably a result of some unrelated path issues in the recreated Solution. Once the path kinks were all ironed out everything went together again.
